//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DTA_DANHSACHTHIETBI
    {
        public string tenmay { get; set; }
        public string maphong { get; set; }
        public string os { get; set; }
        public string cpu { get; set; }
        public string hdd { get; set; }
        public string ssd { get; set; }
        public string ip { get; set; }
        public string ram { get; set; }
        public string urlimage { get; set; }
        public string tennguoidung { get; set; }
        public Nullable<int> namsudung { get; set; }
        public string loaimaytinh { get; set; }
        public string thuonghieu { get; set; }
        public string taikhoan { get; set; }
        public int id { get; set; }
    
        public virtual TBL_DANHMUCPHONGBAN TBL_DANHMUCPHONGBAN { get; set; }
    }
}
