//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IT.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ITEntities : DbContext
    {
        public ITEntities()
            : base("name=ITEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DTA_DANHMUCTHIETBIKHAC> DTA_DANHMUCTHIETBIKHAC { get; set; }
        public virtual DbSet<DTA_DANHSACHTHIETBI> DTA_DANHSACHTHIETBI { get; set; }
        public virtual DbSet<TBL_DANHMUCKHUVUC> TBL_DANHMUCKHUVUC { get; set; }
        public virtual DbSet<TBL_DANHMUCLOAITHIETBI> TBL_DANHMUCLOAITHIETBI { get; set; }
        public virtual DbSet<TBL_DANHMUCNGUOIDUNG> TBL_DANHMUCNGUOIDUNG { get; set; }
        public virtual DbSet<TBL_DANHMUCPHANQUYEN> TBL_DANHMUCPHANQUYEN { get; set; }
        public virtual DbSet<TBL_DANHMUCPHONGBAN> TBL_DANHMUCPHONGBAN { get; set; }
        public virtual DbSet<TBL_DANHMUCSN> TBL_DANHMUCSN { get; set; }
        public virtual DbSet<TBL_DANHMUCTHIETBI> TBL_DANHMUCTHIETBI { get; set; }
        public virtual DbSet<TBL_DANHMUCTHIETBI_AUDIT> TBL_DANHMUCTHIETBI_AUDIT { get; set; }
        public virtual DbSet<TBL_DANHSACHLOAIPHEP> TBL_DANHSACHLOAIPHEP { get; set; }
        public virtual DbSet<TBL_DANHSACHNGAYNGHI> TBL_DANHSACHNGAYNGHI { get; set; }
        public virtual DbSet<TBL_DANHSACHNGAYNGHI_AUDIT> TBL_DANHSACHNGAYNGHI_AUDIT { get; set; }
        public virtual DbSet<TBL_DANHSACHNGUOINHAN> TBL_DANHSACHNGUOINHAN { get; set; }
        public virtual DbSet<TBL_NHANIN> TBL_NHANIN { get; set; }
        public virtual DbSet<TBL_PHIEUGIAONHAN> TBL_PHIEUGIAONHAN { get; set; }
        public virtual DbSet<TBL_TRANGTHAIMAY> TBL_TRANGTHAIMAY { get; set; }
    }
}
