//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_PHIEUGIAONHAN
    {
        public string formid { get; set; }
        public string tennguoidung { get; set; }
        public string userid { get; set; }
        public string maphong { get; set; }
        public string tenmay { get; set; }
        public string serialnumber { get; set; }
        public string ngay { get; set; }
        public string email { get; set; }
        public string loai { get; set; }
    }
}
