//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_TRANGTHAIMAY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_TRANGTHAIMAY()
        {
            this.TBL_DANHMUCTHIETBI = new HashSet<TBL_DANHMUCTHIETBI>();
        }
    
        public int trangthaiid { get; set; }
        public string tentrangthai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_DANHMUCTHIETBI> TBL_DANHMUCTHIETBI { get; set; }
    }
}
