//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_DANHMUCKHUVUC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_DANHMUCKHUVUC()
        {
            this.TBL_DANHMUCPHONGBAN = new HashSet<TBL_DANHMUCPHONGBAN>();
        }
    
        public string makhuvuc { get; set; }
        public string tenkhuvuc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_DANHMUCPHONGBAN> TBL_DANHMUCPHONGBAN { get; set; }
    }
}
