//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_DANHMUCPHANQUYEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_DANHMUCPHANQUYEN()
        {
            this.TBL_DANHMUCNGUOIDUNG = new HashSet<TBL_DANHMUCNGUOIDUNG>();
        }
    
        public string maquyen { get; set; }
        public string tenquyen { get; set; }
        public string chitiet { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_DANHMUCNGUOIDUNG> TBL_DANHMUCNGUOIDUNG { get; set; }
    }
}
