//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_DANHMUCTHIETBI_AUDIT
    {
        public int id { get; set; }
        public System.DateTime ngaythuchien { get; set; }
        public string lenh { get; set; }
        public string mathietbi { get; set; }
        public string maloaithietbi { get; set; }
        public System.DateTime ngay { get; set; }
        public Nullable<bool> xuatkho { get; set; }
        public string serialnumber { get; set; }
        public string ghichu { get; set; }
        public Nullable<System.DateTime> ngaynhan { get; set; }
        public string taikhoan { get; set; }
        public string maphong { get; set; }
        public string makhuvuc { get; set; }
        public string tennguoidung { get; set; }
        public string email { get; set; }
        public string chucvu { get; set; }
        public string tenmay { get; set; }
        public string userid { get; set; }
        public string bpyeucau { get; set; }
        public string emailpyme { get; set; }
        public string sdt { get; set; }
        public Nullable<bool> giaothanhcong { get; set; }
        public string urlimage { get; set; }
        public Nullable<int> trangthaiid { get; set; }
    }
}
