//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_DANHMUCPHONGBAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_DANHMUCPHONGBAN()
        {
            this.DTA_DANHMUCTHIETBIKHAC = new HashSet<DTA_DANHMUCTHIETBIKHAC>();
            this.DTA_DANHSACHTHIETBI = new HashSet<DTA_DANHSACHTHIETBI>();
            this.TBL_DANHMUCNGUOIDUNG = new HashSet<TBL_DANHMUCNGUOIDUNG>();
        }
    
        public string maphong { get; set; }
        public string tenphong { get; set; }
        public string makhuvuc { get; set; }
        public string nguoiduyet { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DTA_DANHMUCTHIETBIKHAC> DTA_DANHMUCTHIETBIKHAC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DTA_DANHSACHTHIETBI> DTA_DANHSACHTHIETBI { get; set; }
        public virtual TBL_DANHMUCKHUVUC TBL_DANHMUCKHUVUC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_DANHMUCNGUOIDUNG> TBL_DANHMUCNGUOIDUNG { get; set; }
    }
}
