//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_DANHMUCNGUOIDUNG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_DANHMUCNGUOIDUNG()
        {
            this.TBL_DANHMUCPHANQUYEN = new HashSet<TBL_DANHMUCPHANQUYEN>();
        }
    
        public string taikhoan { get; set; }
        public string hovaten { get; set; }
        public string sdt { get; set; }
        public bool khoatk { get; set; }
        public int sltruycap { get; set; }
        public System.DateTime ngaydangnhap { get; set; }
        public string maphong { get; set; }
        public Nullable<System.DateTime> ngaykyhopdong { get; set; }
    
        public virtual TBL_DANHMUCPHONGBAN TBL_DANHMUCPHONGBAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_DANHMUCPHANQUYEN> TBL_DANHMUCPHANQUYEN { get; set; }
    }
}
